# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-01 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20171101_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
