# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-01 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20171101_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='note',
            field=models.ManyToManyField(blank=True, to='notes.Note'),
        ),
    ]
