# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-01 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20171101_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.ManyToManyField(blank=True, to='notes.Tag'),
        ),
    ]
