# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-01 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20171101_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='tag',
        ),
    ]
