# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-01 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20171101_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
